"""Stable application errors exposed at the MCP boundary."""

from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    CONFIG_INVALID = "CONFIG_INVALID"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_PATH = "INVALID_PATH"
    PATH_OUTSIDE_PROJECT = "PATH_OUTSIDE_PROJECT"
    SYMLINK_ESCAPE = "SYMLINK_ESCAPE"
    PATH_NOT_FOUND = "PATH_NOT_FOUND"
    PATH_ALREADY_EXISTS = "PATH_ALREADY_EXISTS"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    BLENDER_NOT_FOUND = "BLENDER_NOT_FOUND"
    BLENDER_VERSION_UNSUPPORTED = "BLENDER_VERSION_UNSUPPORTED"
    BLENDER_START_FAILED = "BLENDER_START_FAILED"
    BLENDER_TIMEOUT = "BLENDER_TIMEOUT"
    BLENDER_CANCELLED = "BLENDER_CANCELLED"
    BLENDER_CRASHED = "BLENDER_CRASHED"
    BLENDER_FAILED = "BLENDER_FAILED"
    LIVE_BRIDGE_UNAVAILABLE = "LIVE_BRIDGE_UNAVAILABLE"
    LIVE_BRIDGE_AUTH_FAILED = "LIVE_BRIDGE_AUTH_FAILED"
    ADAPTER_INVALID_RESPONSE = "ADAPTER_INVALID_RESPONSE"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    DISK_SPACE_INSUFFICIENT = "DISK_SPACE_INSUFFICIENT"
    SCENE_REVISION_CONFLICT = "SCENE_REVISION_CONFLICT"
    TRANSACTION_VALIDATION_FAILED = "TRANSACTION_VALIDATION_FAILED"
    TRANSACTION_ROLLED_BACK = "TRANSACTION_ROLLED_BACK"
    SCENE_VALIDATION_BLOCKED = "SCENE_VALIDATION_BLOCKED"
    ASSET_NOT_APPROVED = "ASSET_NOT_APPROVED"
    RENDER_BUDGET_EXCEEDED = "RENDER_BUDGET_EXCEEDED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_STATE_CONFLICT = "JOB_STATE_CONFLICT"
    OUTPUT_QUARANTINED = "OUTPUT_QUARANTINED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class BlenderMCPError(Exception):
    """Expected failure with a stable public error code."""

    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}
